# Generated by Django 4.2 on 2024-12-30 11:40

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(db_column='category_name', max_length=63)),
            ],
            options={
                'db_table': 'product_categories',
                'ordering': ['category_name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(db_column='product_name', max_length=63)),
                ('product_price', models.FloatField(db_column='product_price')),
                ('product_description', models.CharField(db_column='product_description', max_length=512)),
                ('product_image', models.ImageField(db_column='product_image', upload_to='')),
                ('recorde_datetime', models.DateTimeField(auto_now_add=True, db_column='recorde_datetime')),
                ('product_category', models.ForeignKey(db_column='product_category', on_delete=django.db.models.fields.NOT_PROVIDED, to='product.productcategories')),
            ],
            options={
                'db_table': 'products',
                'ordering': ['product_name'],
            },
        ),
    ]
