# Generated by Django 4.2 on 2024-12-31 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategories',
            options={'ordering': ['-category_name']},
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(db_column='p_name', max_length=63),
        ),
    ]
