# Generated by Django 4.2 on 2025-01-02 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_category_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
