# Generated by Django 4.2 on 2025-01-03 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(db_column='product_category', on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='product.productcategories'),
        ),
    ]
