# Generated by Django 4.2 on 2025-01-03 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_product_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(db_column='product_category', on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', related_query_name='category_id', to='product.productcategories'),
        ),
    ]
