# Generated by Django 4.2 on 2024-12-30 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_column='username', max_length=10, unique=True)),
                ('password', models.CharField(db_column='user_password', max_length=20)),
                ('Email', models.EmailField(db_column='user_email', max_length=254, unique=True)),
                ('phone', models.CharField(db_column='user_phone', max_length=20, unique=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
